plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
markdown: kramdown

theme: minima

syntax_highlighter_opts:
  disable: true

collections:
  about:
    output: true
  doc:
    output: true
  tutorial:
    output: true
  FAQ:
    output: true
  resources:
    output: true
  examples:
    output: true
  external:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

twitter:
  username: OSGiAlliance

google_analytics: UA-801425-1

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'README.md'
  - 'CONTRIBUTING.md'
  - 'LICENSE'
  - 'run.sh'
  - '.travis.yml'
  - '/vendor'
