plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
markdown: kramdown
collections:
  book:
    output: true
  qs:
    output: true
  tutorial_base:
    output: true
  tutorial_rsa:
    output: true
  tutorial_iot:
    output: true
  tutorial_wrap:
    output: true
  tutorial_eval:
    output: true
  tutorial_maven:
    output: true
  services:
    output: true
  trains:
    output: true
  videos:
    output: true
  appnotes:
    output: true
  doc:
    output: true
  faq:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

twitter:
  username: OSGiAlliance

google_analytics: UA-801425-1

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'README.md'
  - 'CONTRIBUTING.md'
  - 'LICENSE'
  - 'run.sh'
  - '.travis.yml'
  - '/vendor'
