gems:
  - jekyll-redirect-from
markdown: kramdown
collections:
  book:
    output: true
  qs:
    output: true
  tutorial_base:
    output: true
  tutorial_rsa:
    output: true
  tutorial_iot:
    output: true
  services:
    output: true
  trains:
    output: true
  videos:
    output: true
  appnotes:
    output: true
  doc:
    output: true
  faq:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default


exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'README.md'
  - 'CONTRIBUTING.md'
  - 'LICENSE'
  - 'run.sh'
  - '.travis.yml'
  - '/vendor'
